In [1]:
import pandas as pd
import requests
import json
import csv

In [2]:
url=" https://data.bts.gov/resource/crem-w557.json?$where=auto_sales!=0"

In [3]:
print(requests.get(url))

<Response [200]>

In [4]:
response = requests.get(url)
response_json = response.json()
auto_sales_df=pd.DataFrame(response_json)
recent_sales=auto_sales_df.tail(60)
recent_sales=recent_sales[["date","auto_sales","heavy_truck_sales","light_truck_sales"]]
recent_sales

                        date auto_sales heavy_truck_sales light_truck_sales
593  2016-06-01T00:00:00.000   605400.0           35700.0          908600.0
594  2016-07-01T00:00:00.000   591500.0           30100.0          925900.0
595  2016-08-01T00:00:00.000   580800.0           33600.0          926400.0
596  2016-09-01T00:00:00.000   556300.0           32400.0          874700.0
597  2016-10-01T00:00:00.000   507200.0           29900.0          861300.0
598  2016-11-01T00:00:00.000   509100.0           29800.0          861900.0
599  2016-12-01T00:00:00.000   601300.0           36400.0         1081900.0
600  2017-01-01T00:00:00.000   412900.0           25700.0          726600.0
601  2017-02-01T00:00:00.000   484300.0           28000.0          840900.0
602  2017-03-01T00:00:00.000   590600.0           35200.0          958200.0
603  2017-04-01T00:00:00.000   538500.0           32000.0          880500.0
604  2017-05-01T00:00:00.000   562700.0           34600.0          947900.0
605  2017-06-01T00:00:00.000   521900.0           37700.0          944100.0
606  2017-07-01T00:00:00.000   501900.0           32400.0          907800.0
607  2017-08-01T00:00:00.000   523400.0           38200.0          951600.0
608  2017-09-01T00:00:00.000   535500.0           36100.0          982700.0
609  2017-10-01T00:00:00.000   459200.0           36500.0          891100.0
610  2017-11-01T00:00:00.000   462000.0           35300.0          928300.0
611  2017-12-01T00:00:00.000   496300.0           43500.0         1101100.0
612  2018-01-01T00:00:00.000   366400.0           30700.0          785600.0
613  2018-02-01T00:00:00.000   422300.0           34400.0          872400.0
614  2018-03-01T00:00:00.000   537600.0           40500.0         1110400.0
615  2018-04-01T00:00:00.000   429100.0           37700.0          925400.0
616  2018-05-01T00:00:00.000   513700.0           40000.0         1073800.0
617  2018-06-01T00:00:00.000   483500.0           42900.0         1061100.0
618  2018-07-01T00:00:00.000   417200.0           40200.0          946600.0
619  2018-08-01T00:00:00.000   441300.0           45200.0         1041800.0
620  2018-09-01T00:00:00.000   430300.0           42900.0         1002600.0
621  2018-10-01T00:00:00.000   420400.0           45600.0          940900.0
622  2018-11-01T00:00:00.000   401300.0           39700.0          982100.0
623  2018-12-01T00:00:00.000   447100.0           48100.0         1171800.0
624  2019-01-01T00:00:00.000   353600.0           38300.0          780000.0
625  2019-02-01T00:00:00.000   365500.0           36800.0          886600.0
626  2019-03-01T00:00:00.000   483000.0           43900.0         1116500.0
627  2019-04-01T00:00:00.000   395600.0           46100.0          931600.0
628  2019-05-01T00:00:00.000   455000.0           46600.0         1127200.0
629  2019-06-01T00:00:00.000   440000.0           45100.0         1070500.0
630  2019-07-01T00:00:00.000   382900.0           47400.0         1014100.0
631  2019-08-01T00:00:00.000   434200.0           46600.0         1205100.0
632  2019-09-01T00:00:00.000   339500.0           48500.0          928200.0
633  2019-10-01T00:00:00.000   343800.0           46200.0          991100.0
634  2019-11-01T00:00:00.000   352600.0           35300.0         1051400.0
635  2019-12-01T00:00:00.000   374100.0           46200.0         1138900.0
636  2020-01-01T00:00:00.000   293200.0           31900.0          843300.0
637  2020-02-01T00:00:00.000   346500.0           33100.0         1004100.0
638  2020-03-01T00:00:00.000   264700.0           33400.0          725200.0
639  2020-04-01T00:00:00.000   166400.0           28000.0          548900.0
640  2020-05-01T00:00:00.000   258500.0           23600.0          860600.0
641  2020-06-01T00:00:00.000   251200.0           30400.0          849800.0
642  2020-07-01T00:00:00.000   292600.0           31800.0          944100.0
643  2020-08-01T00:00:00.000   299800.0           36300.0         1018200.0
644  2020-09-01T00:00:00.000   304800.0           38600.0         1036200.0
645  2020-10-01T00:00:00.000   313600.0           40400.0         1045400.0
646  2020-11-01T00:00:00.000   277600.0           36100.0          921500.0
647  2020-12-01T00:00:00.000   332900.0           45900.0         1272600.0
648  2021-01-01T00:00:00.000   247500.0           35400.0          856200.0
649  2021-02-01T00:00:00.000   262200.0           32900.0          935600.0
650  2021-03-01T00:00:00.000   364900.0           45600.0         1235000.0
651  2021-04-01T00:00:00.000   355600.0           38700.0         1178500.0
652  2021-05-01T00:00:00.000   382600.0           38300.0         1195200.0

In [9]:
recent_sales['date']=recent_sales['date'].str.slice(0,4)
recent_sales['auto_sales']

recent_sales.groupby(recent_sales['date']).mean()

AttributeError: 'Series' object has no attribute 'float'